#!/usr/bin/env bash
# Detect the toolchain, record it in state/ENVIRONMENT.md, and resolve deps.
# Safe to run repeatedly. See IOS_READY_MASTER_PLAN.md Section 22.
set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
detect_capabilities

head1 "iOS Ready bootstrap"
info "  os              $IOSREADY_OS"
info "  environment     Tier $IOSREADY_TIER"
info "  swift           $SWIFT_VERSION"
info "  xcode           $XCODE_VERSION"
info "  simulators      $HAS_SIMULATORS"

DEST="(not resolved)"
if [ "$IOSREADY_TIER" = "A" ]; then
  DEST="$("$REPO_ROOT/scripts/ios-destination.sh" 2>/dev/null || echo '(resolution failed)')"
  info "  ios destination $DEST"
fi

mkdir -p "$REPO_ROOT/state"
cat > "$REPO_ROOT/state/ENVIRONMENT.md" << EOM
# Environment

Generated by \`scripts/bootstrap.sh\`. **Do not hand-edit** — regenerate instead.
This file is git-ignored: it describes one machine, not the project.

- Generated at: $(date -u +%Y-%m-%dT%H:%M:%SZ)
- Host OS: $IOSREADY_OS
- **Environment tier: $IOSREADY_TIER** (see master plan Section 22)
- Swift toolchain: $SWIFT_VERSION
- Xcode: $XCODE_VERSION
- iOS simulators available: $HAS_SIMULATORS
- Resolved iOS destination: $DEST

## What this tier can verify

$(case "$IOSREADY_TIER" in
  A) echo "Everything: package tests, content validation, runner with real xcodebuild, iOS build and simulator tests." ;;
  B) echo "Package tests, content validation, runner parser tests. **Not** iOS build or simulator tests." ;;
  C) if [ "$HAS_SWIFT" = true ]; then
       echo "Package tests, content validation, runner parser tests over recorded fixtures. **Not** anything requiring Apple SDKs, simulators, or xcodebuild."
     else
       echo "**No Swift toolchain is installed**, so no Swift code can be compiled or tested here. Only content validation, shell scripts, state integrity, and documentation can be verified. Treat any Swift written in this environment as unverified: mark requirements 'implemented-pending-verification' and queue them in state/VERIFICATION_QUEUE.md."
     fi ;;
esac)
EOM

if [ "$HAS_SWIFT" = true ] && package_exists; then
  head1 "Resolving package dependencies"
  (cd "$REPO_ROOT/Packages/IOSReadyKit" && swift package resolve) && ok "resolved"
fi

head1 "Wrote state/ENVIRONMENT.md"
if [ "$HAS_SWIFT" != true ]; then
  warn "No Swift toolchain found. Swift work cannot be verified in this environment."
  info "  On macOS: install Xcode. On Linux: https://www.swift.org/install/"
fi
